### PR TITLE
Scheduled email reminders

### PR DESCRIPTION
**Pull request by iandees**
For #291.

This is a command that sends reminder emails for carpools scheduled to depart between now and 48 hours into the future. It sends an email to the driver and emails to the riders.

My plan to run this is to use Heroku's scheduler and run it once an hour like so:

```
FLASK_APP=app/email/reminder_tasks.py flask enqueue_scheduled_emails
```

This is a little gross because ideally it would use the existing FLASK_APP but I can't figure out a graceful way to add the command to the existing flask app. Also, we should probably send to all carpools with a departure time 48 hours or less from now, but I can't figure out a way to extract the number of hours between two times using SQLAlchemy.

### CODE REVIEW

**Comment by jmcarp** [comment]
* It looks like `flask-rq2` already has support for cron-like scheduled jobs: https://flask-rq2.readthedocs.io/en/latest/. Do you prefer the heroku scheduler?
* Have time to add some tests? 😁

**Comment by iandees** [comment]
😄 Yes, adding tests was one of the things I wanted to figure out.

I went with this route because @jkriss reminded me that we would have to cancel/update scheduled emails if a carpool was cancelled or changed. This way, we only ever send an email once, even if the carpool changes time. We don't have to remember to un-schedule an email too.

**Comment by jmcarp** [comment]
I like the approach, but it seems like we could do exactly the same thing without depending on heroku scheduler:

```python
@rq.job
def enqueue_scheduled_emails():
    ...
enqueue_scheduled_emails.cron('0 0 0 * *')
```

But maybe I'm misreading.

**Comment by iandees** [comment]
The other aspect of this is that my understanding is we have to run another 24/7 process (`flask rq scheduler`) on top of the worker (`flask rq worker`) to handle the scheduling aspect.

**Pull request merged**
