### PR TITLE
Check for existing email before letting a user log in

### LINKED ISSUE #186: email addresses must be unique
There is an issue with allowing a users to change email address.

There are two scenarios that can happen:
1. locking a user out of their account
2. reducing a user's privilege (removing admin role)

The determining factor is which user id was created first.

Expected results:
1) Email addresses should be unique
2) An email would be sent to old/original account notifying them their email address has been changed
2b) The email sent to the old/original account would have link allowing them to directly log into their account to access their account and reset their email

### PR DESCRIPTION
**Pull request by iandees**
Fixes #186 

Check a user's email address instead of their social ID when logging in. If the email address has already created an account with a different social ID, don't let the new social ID log in.

### CODE REVIEW

**Comment by dryan** [comment]
This all looks good to me. I do agree that we could use clearer copy for the errors.

**Comment by kcaffall** [comment]
@dryan @iandees - can this pull request be merged today? Priority issue #186 is dependent on this issue.

**Comment by iandees** [comment]
I need someone to suggest better text to show to the user.

**Comment by kcaffall** [comment]
When you throw the error, do you know which social app they tried? Something like:
You did not authorize the Facebook login. Try logging in via Goggle login.
or does that give too much away for someone who might be attacking login?

**Comment by iandees** [comment]
We can't easily determine what their other login was. We could say "You've already logged in with another social media account. Please use that one to log in."

**Comment by iandees** [comment]
That does let out a bit of information to potential attackers, but it feels like a decent balance between being informative and secure.

**Pull request merged**
