### PR TITLE
Destination pages

### PR DESCRIPTION
**Pull request by iandees**
For #615 

This adds a page for destinations. It'll list the carpools that are going to the destination and invite the user to create one if there aren't any.

### CODE REVIEW

**Comment by iandees** [comment]
This is what the empty case looks like:

image

This is what it looks like with a carpool:

image

**Comment by iandees** [comment]
The migration isn't needed ... I was going to provide friendly-looking names for the destination URLs but haven't wired that in yet. If that feature would be useful I can work with you more on figuring out what's wrong with the migration.

**Comment by dryan** [comment]
At least for me locally it's throwing an exception that destinations.slug doesn't exist.

I don't think that feature is needed, UUIDs would be fine.

**Comment by jillh510** [comment]
I agree with @dryan about the prettified names not being needed.

**Comment by jillh510** [comment]
@iandees did the migration stuff get pulled?

**Comment by iandees** [comment]
Removed the slug and migration. 👍

**Pull request merged**
