### PR TITLE
Check test coverage from travis.

### PR DESCRIPTION
**Pull request by jmcarp**
Still need to pick a test coverage service so we can get feedback on PRs and a badge. I've had good experiences with codecov, but codeclimate looks good too. WDYT @iandees ?

### CODE REVIEW

**Comment by iandees** [comment]
I think I've used codecov in the past but have no strong opinion. If you want to try codeclimate go for it!

**Comment by jmcarp** [comment]
Want to give this a try @iandees ? You'll have to set up code climate for the repo and add your encrypted api key to the travis manifest to replace mine.

**Comment by iandees** [comment]
I requested access for codecov to RagtagOpen for this project. If that goes through, I'll look into updating this PR.

**Comment by iandees** [comment]
I'm going to close this for now. I'd like to see coverage reports, but it's been so long and this PR has conflicts.

**Pull request closed without merging**
