### PR TITLE
Add test harness and initial models tests.

### PR DESCRIPTION
**Pull request by jmcarp**
* [x] Test harness
* [x] >0 models tests
* [x] >0 forms tests
* [x] >0 functional tests

Borrowed from the awesome https://github.com/sloria/cookiecutter-flask. Thanks @sloria!

### CODE REVIEW

**Comment by iandees** [comment]
Wahoo! Thanks for starting this!

**Comment by jmcarp** [comment]
Ready for review @iandees. If you have a preferred ci service, I can set that up too. For public ci services, I'm most familiar with travis and circle, but heroku ci could work too if you're trying to minimize number of services.

**Comment by iandees** [comment]
Thanks @jmcarp! I'm going to try Heroku's CI thing and see how it works.

**Comment by iandees** [comment]
Actually, Heroku CI is $10/month and doesn't seem to add much. Let's try Travis.

**Pull request merged**
