### PR TITLE
first pass at redirecting new users to previous pages

### PR DESCRIPTION
**Pull request by tkell**
Hello @joearasin, @iandees, @jillh510, this is a first pass with no test at #482 – a join link.

We basically already have these, just by sending the user to `carpools/<carpool-id>`.  Thanks to Joe and Ian fixing the login redirect, this works for existing users who are not logged in.  This PR will make things work for new users.  

I've done this by adding a field to the session object.  I _think_ this is secure, but I am not certain.  What do y'all think / is there a better way to do this?

### CODE REVIEW

**Comment by joearasin** [comment]
For security, the big bug is that we need to get rid of the mutating GETs.

We shouldn't need to track the referer, though... next should already be in the session. Is something removing it improperly?

**Comment by joearasin** [comment]
Ahh never mind -- I get it. This is on explicitly clicking "log in" when you're not already logged in so you're taken back to where you came from, rather than when you're trying to do something that needs auth and get sent to the login.

**Comment by tkell** [comment]
@joearasin, yeah it is the referrer's referrer (or maybe even three levels deep?).  

I don't totally follow you on what a "mutating GET" is - do you mean the fact that you click on something like `http://localhost:5000/carpools/279890a4-5c3f-415b-b25e-e343577fd397/join`, do you account creation, and then get eventually redirected to `http://localhost:5000/carpools/279890a4-5c3f-415b-b25e-e343577fd397`?

**Comment by joearasin** [comment]
@tkell exactly -- if you can redirect someone to http://localhost:5000/carpools/279890a4-5c3f-415b-b25e-e343577fd397/join which then executes the join, there's a CSRF vulnerability where an adversary were to put a link to something like `<iframe url="http://localhost:5000/carpools/279890a4-5c3f-415b-b25e-e343577fd397/join">` in an html page, they could force users to join a carpool

**Comment by tkell** [comment]
Oh, got it - "mutating" as in mutating the state of the database, not mutating the URL that the user goes to.

I think we're good, at least in the case.  If a user clicks on `http://localhost:5000/carpools/279890a4-5c3f-415b-b25e-e343577fd397/newrider` from `http://localhost:5000/carpools/279890a4-5c3f-415b-b25e-e343577fd397`, they get sent to account creation, and then get sent back to `http://localhost:5000/carpools/279890a4-5c3f-415b-b25e-e343577fd397` – without joining the carpool.

Hmm, if a user goes to directly to `http://localhost:5000/carpools/279890a4-5c3f-415b-b25e-e343577fd397/newrider`, they won't have anywhere to get redirected to.  It looks like they stay on the profile page, which seems OK?

(I thought the url was /join, it is actually /newrider)

**Comment by iandees** [comment]
@joearasin we worked pretty hard a while ago to get rid of the mutating GETs. If you spot more please file tickets.

**Pull request merged**
